In [1]:
import pandas as pd
from pathlib import Path

# Display all columns
pd.set_option("display.max_columns", None)

# Display wider tables
pd.set_option("display.width", 1000)

DATASET_PATH = Path("datasets")

In [2]:
def preview_dataset(filename, rows=5):
    df = pd.read_csv(DATASET_PATH / filename)

    print("=" * 80)
    print(filename)
    print("=" * 80)
    print(f"Shape : {df.shape}")
    print()

    display(df.head(rows))

    return df

Suppliers

In [3]:
suppliers = preview_dataset("suppliers.csv")

================================================================================
suppliers.csv
================================================================================
Shape : (2000, 6)

   supplier_id          supplier_name country       contact_email                phone  rating
0            1           Elite Supply   Japan  sales1@example.com         885-917-2662    4.14
1            2    United Distribution   India  sales2@example.com    (829)950-2298x951    3.90
2            3         United Trading   China  sales3@example.com  +1-476-861-4758x178    4.30
3            4          Prime Trading   India  sales4@example.com     001-839-336-5038    4.96
4            5  National Distribution   China  sales5@example.com        (726)986-6264    3.55

Warehouses

In [4]:
warehouses = preview_dataset("warehouses.csv")

================================================================================
warehouses.csv
================================================================================
Shape : (20, 5)

   warehouse_id warehouse_name         city country  capacity
0             1      North Hub     New York     USA    201984
1             2      South Hub      Chicago     USA    200296
2             3       East Hub       Dallas     USA     84160
3             4       West Hub  Los Angeles     USA    237042
4             5    Central Hub      Seattle     USA    181253

Customers

In [5]:
customers = preview_dataset("customers.csv")

================================================================================
customers.csv
================================================================================
Shape : (50000, 13)

   customer_id first_name last_name                  email              phone gender date_of_birth                city          state       country  postal_code signup_date customer_segment
0            1   Michelle    Atkins  customer1@example.com       409-722-3557      F    2005-12-15          North Joel  West Virginia         Japan        74132  2023-02-28             Gold
1            2    Stephen    Brooks  customer2@example.com       411-949-8908      M    1913-03-13  East Josephborough       Delaware     Australia        26574  2023-04-26           Bronze
2            3     Nathan    Rivers  customer3@example.com  (851)410-7459x760      M    2023-04-13        North Robert     New Jersey        Canada        58982  2022-12-26           Silver
3            4      Debra    Morris  customer4@example.com   391.616.6049x287      F    1987-08-09       West Jennifer         Kansas  Saudi Arabia        31710  2026-03-30         Platinum
4            5       Adam    Holmes  customer5@example.com         7674363670      M    1944-04-04        Matthewsfurt   South Dakota         Japan        80167  2023-07-04           Bronze

Products

In [6]:
products = preview_dataset("products.csv")

================================================================================
products.csv
================================================================================
Shape : (10000, 12)

   product_id            product_name  brand category  subcategory                                        description    price     cost  color  weight_kg  rating  supplier_id
0           1  Packt Programming 7652  Packt    Books  Programming  Packt Programming designed for high performanc...  1115.13  1404.88  Black      15.44     4.5          708
1           2       Nike Fitness 8233   Nike   Sports      Fitness  Nike Fitness designed for high performance and...   831.32   750.65   Gray       7.03     4.8          388
2           3     IKEA Furniture 1769   IKEA     Home    Furniture  IKEA Furniture designed for high performance a...   817.49   133.48    Red      13.57     4.9         1731
3           4      Zara Clothing 6353   Zara  Fashion     Clothing  Zara Clothing designed for high performance an...  1503.95   643.81    Red       2.72     4.7          605
4           5       Nike Fitness 4594   Nike   Sports      Fitness  Nike Fitness designed for high performance and...  1468.21  1394.50   Gray      10.51     3.6         1940

Orders

In [7]:
orders = preview_dataset("orders.csv")

================================================================================
orders.csv
================================================================================
Shape : (250000, 9)

   order_id  customer_id           order_date      status shipping_city shipping_country  shipping_cost  discount  total_amount
0         1        16515  2025-07-01 10:19:33   Cancelled         Dubai              UAE          25.61     77.81       3804.25
1         2        15161  2024-01-08 04:29:38   Delivered        London               UK          39.54     36.96       1979.04
2         3        10675  2024-09-22 05:26:24  Processing     Singapore        Singapore          18.62     26.35       3437.74
3         4        16727  2024-04-01 20:35:13   Delivered        Berlin          Germany          29.14     52.19       4503.28
4         5         7314  2026-06-08 20:58:34   Delivered       Chicago              USA          36.42     85.48       3547.16

Order Items

In [8]:
order_items = preview_dataset("order_items.csv")

================================================================================
order_items.csv
================================================================================
Shape : (749436, 8)

   order_item_id  order_id  product_id  quantity  unit_price  discount_pct  discount_amount  total_price
0              1         1         558         5      227.05             0             0.00      1135.25
1              2         1        7679         3     2288.13             5           343.22      6521.17
2              3         1        3672         1     1031.70            15           154.75       876.95
3              4         2        7557         5      405.19             5           101.30      1924.65
4              5         2        1493         5      168.83            15           126.62       717.53

Payments

In [9]:
payments = preview_dataset("payments.csv")

================================================================================
payments.csv
================================================================================
Shape : (250000, 8)

   payment_id  order_id payment_method payment_status         payment_date   amount currency transaction_reference
0           1         1    Credit Card      Completed  2025-07-01 10:19:33  3804.25      USD         TXN0000000001
1           2         2     Debit Card      Completed  2024-01-08 04:29:38  1979.04      USD         TXN0000000002
2           3         3         PayPal      Completed  2024-09-22 05:26:24  3437.74      USD         TXN0000000003
3           4         4     Debit Card      Completed  2024-04-01 20:35:13  4503.28      USD         TXN0000000004
4           5         5    Credit Card      Completed  2026-06-08 20:58:34  3547.16      USD         TXN0000000005

Inventory

In [10]:
inventory = preview_dataset("inventory.csv")

================================================================================
inventory.csv
================================================================================
Shape : (200000, 8)

   inventory_id  warehouse_id  product_id  quantity_on_hand  reorder_level  max_stock  unit_cost  inventory_value
0             1             1           1               111             47        590    1404.88        155941.68
1             2             1           2               111             44        988     750.65         83322.15
2             3             1           3               306             39        522     133.48         40844.88
3             4             1           4               276             72        979     643.81        177691.56
4             5             1           5               220             27        724    1394.50        306790.00

Reviews

In [11]:
reviews = preview_dataset("reviews.csv")

================================================================================
reviews.csv
================================================================================
Shape : (150000, 8)

   review_id  customer_id  product_id  rating        review_title                                 review_text  verified_purchase review_date
0          1        20536        7517       5     Worth the Money              Highly recommend this product.              False  2024-10-11
1          2        38310        8651       5           Very Good                 Would definitely buy again.               True  2025-02-28
2          3        23666        9768       5  Highly Recommended  Excellent build quality and fast delivery.               True  2026-01-12
3          4        28482        7735       4     Could Be Better              Amazing product for the price.              False  2023-08-12
4          5        18347        5472       1   Fantastic Quality                        Would not recommend.              False  2025-09-01

In [1]:
from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("Retail Dataset") \
    .getOrCreate()

reviews = spark.read.csv(
    "datasets/reviews.csv",
    header=True,
    inferSchema=True
)

reviews.createOrReplaceTempView("reviews")

spark.sql("SELECT * FROM reviews where verified_purchase ='false' and review_date > '2025-01-01'").show()

+---------+-----------+----------+------+--------------------+--------------------+-----------------+-----------+
|review_id|customer_id|product_id|rating|        review_title|         review_text|verified_purchase|review_date|
+---------+-----------+----------+------+--------------------+--------------------+-----------------+-----------+
|        5|      18347|      5472|     1|   Fantastic Quality|Would not recommend.|            false| 2025-09-01|
|        7|       4394|      1592|     3|           Very Good|The product is ok...|            false| 2025-05-25|
|       17|      34819|      8691|     4|           Very Good|Works exactly as ...|            false| 2025-03-19|
|       22|      46700|      7368|     2|     Could Be Better|Not worth the price.|            false| 2025-03-02|
|       23|      33612|      4080|     1|           Very Good| Poor build quality.|            false| 2025-03-30|
|       30|      26983|      5757|     2|Exceeded Expectat...|Stopped working a...|            false| 2025-12-24|
|       37|      42071|      6499|     1|   Excellent Product|Would not recommend.|            false| 2025-10-09|
|       49|      34741|      9980|     4|           Very Good|Works exactly as ...|            false| 2026-07-02|
|       51|      27516|      5423|     4|           Very Good|Highly recommend ...|            false| 2026-02-03|
|       52|      30494|      4881|     3|     Worth the Money|The product is ok...|            false| 2026-07-05|
|       62|      12626|      6089|     4|   Excellent Product|Works exactly as ...|            false| 2026-05-31|
|       63|       5299|       299|     2|           Very Good|Would not recommend.|            false| 2026-05-25|
|       66|      25030|      3344|     3|          Good Value|Good but not exce...|            false| 2025-10-08|
|       67|       4143|      4189|     2|     Could Be Better|Stopped working a...|            false| 2026-05-05|
|       71|      19869|      5960|     3|   Fantastic Quality|Works fine but ex...|            false| 2025-08-05|
|       73|      38809|      9605|     5|          Good Value|Outstanding quali...|            false| 2026-02-08|
|       74|      15742|      9936|     3|     Could Be Better|Average quality f...|            false| 2026-05-28|
|       75|       9989|      9529|     3|           Very Good|Average quality f...|            false| 2026-05-15|
|       80|      45629|      3182|     4|          Good Value|Five stars withou...|            false| 2025-06-11|
|       86|      29656|      4133|     4|   Fantastic Quality|Amazing product f...|            false| 2025-01-26|
+---------+-----------+----------+------+--------------------+--------------------+-----------------+-----------+
only showing top 20 rows

In [2]:
spark.sql("SELECT * FROM reviews where verified_purchase ='false' and review_date > '2025-01-01'").show()

+---------+-----------+----------+------+--------------------+--------------------+-----------------+-----------+
|review_id|customer_id|product_id|rating|        review_title|         review_text|verified_purchase|review_date|
+---------+-----------+----------+------+--------------------+--------------------+-----------------+-----------+
|        5|      18347|      5472|     1|   Fantastic Quality|Would not recommend.|            false| 2025-09-01|
|        7|       4394|      1592|     3|           Very Good|The product is ok...|            false| 2025-05-25|
|       17|      34819|      8691|     4|           Very Good|Works exactly as ...|            false| 2025-03-19|
|       22|      46700|      7368|     2|     Could Be Better|Not worth the price.|            false| 2025-03-02|
|       23|      33612|      4080|     1|           Very Good| Poor build quality.|            false| 2025-03-30|
|       30|      26983|      5757|     2|Exceeded Expectat...|Stopped working a...|            false| 2025-12-24|
|       37|      42071|      6499|     1|   Excellent Product|Would not recommend.|            false| 2025-10-09|
|       49|      34741|      9980|     4|           Very Good|Works exactly as ...|            false| 2026-07-02|
|       51|      27516|      5423|     4|           Very Good|Highly recommend ...|            false| 2026-02-03|
|       52|      30494|      4881|     3|     Worth the Money|The product is ok...|            false| 2026-07-05|
|       62|      12626|      6089|     4|   Excellent Product|Works exactly as ...|            false| 2026-05-31|
|       63|       5299|       299|     2|           Very Good|Would not recommend.|            false| 2026-05-25|
|       66|      25030|      3344|     3|          Good Value|Good but not exce...|            false| 2025-10-08|
|       67|       4143|      4189|     2|     Could Be Better|Stopped working a...|            false| 2026-05-05|
|       71|      19869|      5960|     3|   Fantastic Quality|Works fine but ex...|            false| 2025-08-05|
|       73|      38809|      9605|     5|          Good Value|Outstanding quali...|            false| 2026-02-08|
|       74|      15742|      9936|     3|     Could Be Better|Average quality f...|            false| 2026-05-28|
|       75|       9989|      9529|     3|           Very Good|Average quality f...|            false| 2026-05-15|
|       80|      45629|      3182|     4|          Good Value|Five stars withou...|            false| 2025-06-11|
|       86|      29656|      4133|     4|   Fantastic Quality|Amazing product f...|            false| 2025-01-26|
+---------+-----------+----------+------+--------------------+--------------------+-----------------+-----------+
only showing top 20 rows